### ISSUE TITLE
[window decorations]: fix "shadow artifact" when moving windows

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.12#64]
still seen on reviews as well as locally:
https://www.youtube.com/watch?v=IfbHVApLbyg&feature=youtu.be&t=79
https://www.youtube.com/watch?v=znvuZuqtVaA&feature=youtu.be&t=19
also different theme:
https://www.youtube.com/watch?v=znvuZuqtVaA&feature=youtu.be&t=441

Any idea how to solve this and also possibly related the appearance of the window theme frame a few seconds later than the content of the window appearing?

**Comment by notmart** [comment]
I've found a way to reliably reproduce it on different systems:
* use an aurorae decoration (breeze and the other native ones don't have the problem)
* disable some kwin effects:
    * maximize animation
    * fade in
    * translucency
(as those effects cause some extra repaints that would clean up the screen.)
* maximize a window (better if it's the only window in the desktop)
* unmaximize it by quickly dragging the titlebar away
* sometimes, when the mouse button is released, a piece of leftover decoration remains in an intermediate position

**Comment by notmart** [comment]
replacing this queued connection with a direct invocation  seems to make things better here
https://paste.kde.org/pydvafhkk

**Comment by davidedmundson** [comment]
I think you've found the bug (good work btw), but I don't think the solution is quite that simple.

On xrender it's rendering the shadows first presumably as the main deco could paint over them. 
On OpenGL it's getting the quads for both, then rendering both.

The Auorae code is updating the shadow inside decoration::paint   - basically updating the decoration whilst it's painting the decoration. Queuing is techincally wrong (hence our first glitch) but doing it there causes problems too - my black flicker on refresh.

**Comment by notmart** [comment]
if i compare it with what oxygen or breeze are doing, they are regenerating the shadow on the signal
KDecoration2::DecoratedClient::activeChanged, which is probably the correct thing to do.
if i do the same in fact the glitch is gone, but, since the pixmaps are generated with another timer, i get the outdated shadow pixmap, so when the window is active i get a shadow that look inactive and vice versa, because is redone too soon before the graphics are repainted.

**Comment by davidedmundson** [comment]
I built on top of that idea and moved things earlier.

https://paste.kde.org/ppfo3gb3b

We go from QtQuick to a pixmap buffer every update.
  ::paint simply does a copy of that buffer.

We can update the shadow when we update the buffer. Code seems like it should do things all in the right order now. 

It's a bigger rewrite, but I think it's more correct.

**Comment by notmart** [comment]
seems the problem is still happening here :/

**Comment by notmart** [comment]
investigation continues:
in
void AbstractClient::addRepaintDuringGeometryUpdates()

the first time a window moves, that's when the bug occurs, i get a smaller geometry.
that's a debug of the values m_visibleRectBeforeGeometryUpdate and deco_rect
QRect(274,423 1062x552) QRect(256,410 1092x582)
QRect(256,410 1092x582) QRect(255,410 1092x582)
QRect(255,410 1092x582) QRect(251,409 1092x582)
QRect(251,409 1092x582) QRect(248,409 1092x582)

that suggests the first time the shadow was *not* taken into account
that brings us back to the shadow getting set too late, so i wonder if is possible to make kwin to think the window geometry is changed when the shadow for aurorae "arrives", that's what actually happens.. in some sense

**Comment by notmart** [comment]
this https://phabricator.kde.org/D5078 seems to reliably fix the issue for me, at least the leftover shadow at first move, which with kwinrc from maui (https://github.com/maui-common/maui-settings-theming/blob/master/usr/share/default-settings/plasma5-profile/kwinrc) is easily reproduced.

**Comment by notmart** [comment]
pushed it, so still needs testing on maui.
it's on master, so should reach devel unstable shortly

**Comment by star-buck** [comment]
which release should this be in?

**Comment by notmart** [comment]
5.9.5: 25th april
 and 5.10.0 30 may
https://community.kde.org/Schedules/Plasma_5
